globals:
  - id: g_wifi_connected
    type: bool
    initial_value: "false"

ota:
  - platform: esphome
    password: !secret esphome_admin_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

captive_portal:

logger:

api:
  encryption:
    key: !secret esphome_api_key
  id: espapi
  reboot_timeout: 5min
