mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: !secret mqtt_client_id
  topic_prefix: null
  log_topic: null
  keepalive: 5s
  reboot_timeout: 0s
  discover_ip: False
  discovery: False
  discovery_retain: False
  birth_message:
    topic: !secret mqtt_lastwill_topic
    payload: connected
  will_message:
    topic: !secret mqtt_lastwill_topic
    payload: disconnected

interval:
  - interval: 5s
    then:
      - if:
          condition:
            lambda: 'return id(charging_basic_energy).state > 0 && id(charging_basic_status).state != "" && id(charging_basic_seconds).state > 0;'
          then:
            - mqtt.publish_json:
                topic: !secret mqtt_device_publish_topic
                payload: |-
                  root["charging-energy"] = id(charging_basic_energy).state;
                  root["charging-seconds"] = id(charging_basic_seconds).state;
                  root["charging-state"] = id(charging_basic_status).state;
